# Generated by Django 4.1.2 on 2025-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
